### ISSUE TITLE
使用强化学习时，训练的时间过长

### ISSUE THREAD

**Issue by deng1604** [SKD-HPC/TSGET#2]
我在运行IU-Xray数据集时的强化学习的代码，epoch从129到151，时间是09:22:11到16:43:01，22个epoch，花费了7个小时。正常情况下，一个epoch大概是5分钟的。这强化学习也太消耗时了吧。因为本身还需要先跑一遍模型，再使用强化学习进行微调的。总之，太耗费时间了，不敢想象MIMIC-CXR数据集，需要跑多少时间。
另外，在IU-Xray数据集上面，使用强化学习进行微调时，性能（BLEU1）由原来的42，变为了38左右，并没有得到提升。虽然说方差是由影响的，但是，我觉得不应该导致精度下降吧

**Comment by SKD-HPC** [comment]
您好！您提出的两个问题都是客观存在的。首先，在较小的IU数据集上，性能波动确实大，有时会出现性能降低的情况。即使不采用强化学习，采用不同随机数种子得到的结果，性能波动也大。但是在大规模MIMIC数据集上性能提升较高，且未出现性能降低的情况。其次，训练时间长是无法避免的。好在，IU数据集小，很快就能训练完。MIMIC数据集上，仅需要训练几个Epoch（甚至一个Epoch），即获得较高的性能。您有任何疑问可以随时联系我yxl1620159241@163.com。

**Comment by deng1604** [comment]
好的，谢谢您的回复。那我想问一下，你们使用的是什么显卡，运行IU-Xray、MIMIC-CXR需要花费了多少时间呢？因为我没有训练MIMiC-CXR数据集。然后，大概在MIMIC-CXR上面，你使用的epoch的数目是多少呢？

**Comment by SKD-HPC** [comment]
您好！我用的是非常古老的P100显卡。MIMIC数据集，建议Epoch设置为1~5。至于训练时间，在MIMIC数据集上，有的模型要两天跑完一个Epoch，而有些模型要半个月跑完一个模型。因为我的显卡是八年前的产物了，所以跑的非常慢。

**Comment by deng1604** [comment]
好的，非常感谢❤️

> MIMIC数据集，建议Epoch设置为1~5。

这里的epoch数，是指的一开始的训练吗？还是之后的微调阶段呢

**Comment by SKD-HPC** [comment]
微调阶段。

**Comment by deng1604** [comment]
🆗谢谢啦 🌹
